### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/gganimate#236]
- [x] Add object permanence section to all transition docs
- [x] Describe all frame variables in the transition docs (including `frame`, `frames`, `progress`, and `data`)
- [x] Improve enter/exit docs
- [x] Add note about using `stat()` inside transitions
- [x] Include examples in all high-level docs
- [x] Add introductory vignette
- [ ] Add vignette on rendering and saving
- [x] pkgdown site
- [ ] blogpost summarising useR talk
